### ISSUE TITLE
xFit error

### ISSUE THREAD

**Issue by dasiav7** [jmpsteen/medflex#11]
Is the xFit in medflex only for linear regression now? 

`
impData <- neImpute(Histology ~ Cigarette + med1 * med2 + Age + Gender + Stage + Race, family = binomial("logit"), nMed = 2, data = data2)`

` expFit <- glm(Cigarette ~ Age + Gender + Stage + Race, family = binomial("logit"), data = data2)`

` neMod <- neModel(Histology ~ Cigarette0 + Cigarette1, family = binomial
[data2.zip](https://github.com/jmpsteen/medflex/files/1133647/data2.zip)
("logit"), expData = impData, xFit = expFit, se = "robust")`

gives：

`Error in switch(family, gaussian = function(x) dnorm(x, mean = predictFUN(xFit,  : 
  EXPR must be a length 1 vector
`

[data2.zip](https://github.com/jmpsteen/medflex/files/1133648/data2.zip)

**Comment by jmpsteen** [comment]
No, it definitely is not only for linear regression. As a matter of fact, inverse weighting was originally developed for binary exposures, so it should definitely work for logistic regression models as well.

This seems to have been a bug specifically related to the `family` argument specification of the exposure/propensity score model. 

While this piece of code did not work
```
expFit <- glm(attbin ~ gender + educ + age, family = binomial("logit"), data = UPBdata)
impData <- neImpute(UPB ~ factor(attbin) * negaff + gender + educ + age, 
                    family = binomial, data = UPBdata)
neMod <- neModel(UPB ~ attbin0 * attbin1, family = binomial, 
                 expData = impData, xFit = expFit, se = "robust")
```

this did (simply by replacing `family = binomial('logit')` by `family = binomial`
```
expFit <- glm(attbin ~ gender + educ + age, family = binomial, data = UPBdata)
impData <- neImpute(UPB ~ factor(attbin) * negaff + gender + educ + age, 
                    family = binomial, data = UPBdata)
neMod <- neModel(UPB ~ attbin0 * attbin1, family = binomial, 
                 expData = impData, xFit = expFit, se = "robust")
```

This is now fixed by some internal code modifications (referring to formula objects inside functions).

**Comment by anup545587** [comment]
Hi, 
datimp1 <- neImpute(Srhrecodedop ~ education_lvls+smokingstatus*new_bmi_binned*rpa3lvls+STARTALD,
                     family = binomial("logit"), nMed = 3, data = new)
expFit <- glm( education_lvls~ STARTALD, family = binomial("logit"), data = new)
nemodd1 <- neModel(Srhrecodedop ~ education_lvls0+education_lvls1 + STARTALD,
                  family = binomial("logit"),  expData = datimp1,xFit = expFit, se="robust")
Error: cannot find valid starting values: please specify some

education_lvls is a categorical variable. cannot figure out the source of error.
